"""``fsctl image-context`` — build-generated worker-image context.

Turns an exact, verified feature wheel into a minimal, transparent ``docker build``
context for a customer feature worker image:

    ClearFeature base worker image + one approved feature wheel = customer worker image

The context contains the wheel itself, a build-generated ``feature-artifact.json``
, the registry extracted from the verified
wheel, and a Dockerfile that re-verifies the wheel SHA-256 during the build (the build
fails on mismatch), installs the wheel with ``--no-deps --offline`` into the base image's
environment, preserves the original wheel at the content-addressed location the runtime
verifier re-hashes, and sets the ENV so the image is self-describing.

No image-building service, no runtime installation, no credentials.
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

from fintech_feature_platform.cli.artifact import (
    WheelBuildError,
    build_wheel,
    install_and_test_wheel,
    sha256_file,
)
from fintech_feature_platform.cli.manifest import (
    MANIFEST_FILENAME,
    FeatureProjectManifest,
    ManifestError,
    load_manifest,
)

# Image locations (the runtime contract's source of truth).
ARTIFACT_DIR = "/opt/clearfeature/feature-artifacts"
MANIFEST_IMAGE_PATH = "/etc/clearfeature/feature-artifact.json"
REGISTRY_IMAGE_PATH = "/etc/clearfeature/registry.yaml"

_DOCKERFILE = """\
# Customer feature worker image (generated by `fsctl image-context` ).
#
#   ClearFeature base worker image + one approved feature wheel = this image.
#
# The build re-verifies the wheel SHA-256 (fails on mismatch), installs the exact wheel
# with --no-deps --offline (no dependency resolution, no network), preserves the original
# wheel for runtime re-hashing, and ships the build-generated feature-artifact.json.
# No runtime pip install; workers must be restarted to adopt a new bundle/image.

ARG BASE_IMAGE={base_image}
FROM ${{BASE_IMAGE}}

USER root

# The original immutable wheel, content-addressed; the runtime verifier re-hashes it.
COPY {filename} {wheel_image_path}

# Fail the image build if the wheel bytes do not match the published SHA-256.
RUN echo "{sha_hex}  {wheel_image_path}" | sha256sum -c -

# Install the exact wheel only: no dependency resolution, no network access.
RUN uv pip install --python /app/.venv/bin/python --no-deps --offline {wheel_image_path}

# Build-generated runtime evidence + the registry extracted from the verified wheel.
COPY feature-artifact.json {manifest_image_path}
COPY registry.yaml {registry_image_path}
RUN chmod -R a+rX /opt/clearfeature /etc/clearfeature

USER fsp

# Self-describing runtime contract (override per deployment if needed).
ENV FSP_REGISTRY_PATH={registry_image_path} \\
    FSP_UDF_PROVIDER={provider} \\
    FSP_FEATURE_ARTIFACT_MANIFEST={manifest_image_path}
"""


class ImageContextError(RuntimeError):
    """Raised when the image build context cannot be generated safely."""


def _extract_registry(wheel: Path, registry_rel: str) -> str:
    try:
        with zipfile.ZipFile(wheel) as zf:
            return zf.read(registry_rel).decode("utf-8")
    except (KeyError, zipfile.BadZipFile) as exc:
        raise ImageContextError(
            f"wheel does not contain the project registry {registry_rel!r}: {exc}"
        ) from exc


def build_image_context(
    project_dir: str | Path,
    out_dir: str | Path,
    *,
    wheel: str | Path | None = None,
    base_image: str = "fsp-app:latest",
    work_dir: str | Path | None = None,
) -> dict:
    """Generate the customer worker-image build context. Returns a safe descriptor.

    The wheel is built from the project when not supplied, then installed and
    golden-tested in isolation before anything is written — the context
    only ever contains a verified wheel.
    """
    project = Path(project_dir)
    out = Path(out_dir)
    manifest_path = project / MANIFEST_FILENAME
    if not manifest_path.is_file():
        raise ImageContextError(f"no {MANIFEST_FILENAME} in {project}")
    manifest: FeatureProjectManifest = load_manifest(manifest_path)
    missing = [
        field
        for field, value in (
            ("registry", manifest.registry),
            ("tests", manifest.tests),
            ("udf_provider", manifest.udf_provider),
            ("project", manifest.project or manifest.package),
        )
        if value is None
    ]
    if missing:
        raise ImageContextError(f"{MANIFEST_FILENAME} missing: {missing}")
    if out.exists() and any(out.iterdir()):
        raise ImageContextError(f"context directory {out} is not empty")

    wheel_path = (
        Path(wheel)
        if wheel is not None
        else build_wheel(project, Path(work_dir or out.parent) / ".image-context-dist")
    )
    sha256 = sha256_file(wheel_path)
    result = install_and_test_wheel(
        wheel_path,
        provider=manifest.udf_provider,
        registry_rel=manifest.registry,
        tests_rel=manifest.tests,
        manifest_project=manifest.project or manifest.package,
    )
    identity = result["identity"]

    sha_hex = sha256.split(":", 1)[-1]
    filename = wheel_path.name
    wheel_image_path = f"{ARTIFACT_DIR}/{sha_hex}/{filename}"

    # Build-generated runtime evidence.
    feature_artifact_manifest = {
        "format_version": 1,
        "name": identity["name"],
        "version": identity["version"],
        "provider": manifest.udf_provider,
        "filename": filename,
        "sha256": sha256,
        "wheel_path": wheel_image_path,
    }
    if manifest.requires_core:
        feature_artifact_manifest["requires_core"] = manifest.requires_core

    out.mkdir(parents=True, exist_ok=True)
    (out / filename).write_bytes(wheel_path.read_bytes())
    (out / "feature-artifact.json").write_text(
        json.dumps(feature_artifact_manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (out / "registry.yaml").write_text(
        _extract_registry(wheel_path, manifest.registry), encoding="utf-8"
    )
    (out / "Dockerfile").write_text(
        _DOCKERFILE.format(
            base_image=base_image,
            filename=filename,
            wheel_image_path=wheel_image_path,
            sha_hex=sha_hex,
            provider=manifest.udf_provider,
            manifest_image_path=MANIFEST_IMAGE_PATH,
            registry_image_path=REGISTRY_IMAGE_PATH,
        ),
        encoding="utf-8",
    )
    return {
        "ok": True,
        "context_dir": str(out),
        "name": identity["name"],
        "version": identity["version"],
        "filename": filename,
        "feature_artifact_sha256": sha256,
        "wheel_image_path": wheel_image_path,
        "base_image": base_image,
        "build_command": f"docker build -t <your-feature-worker-tag> {out}",
    }


__all__ = ["build_image_context", "ImageContextError", "ManifestError", "WheelBuildError"]
